FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY . .

EXPOSE 5001

ENV KAFKA_HOST=kafka
ENV CASSANDRA_HOST=cassandra
ENV PROJECT_HOME=/app

CMD ["python3", "predict_flask.py"]
